# Generated by Django 5.2.5 on 2025-08-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(db_index=True, max_length=16, unique=True)),
                ('appliance', models.CharField(max_length=64)),
                ('problem', models.CharField(max_length=64)),
                ('problem_other', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=255)),
                ('time_window', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening'), ('Flexible', 'Flexible')], max_length=16)),
                ('appointment_date', models.DateField()),
                ('serial_number', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(default='NEW', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
