# Generated by Django 5.1.4 on 2025-09-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='intakelog',
            name='appliance',
        ),
        migrations.AddField(
            model_name='intakelog',
            name='brand',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intakelog',
            name='under_warranty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='intakelog',
            name='ticket_id',
            field=models.CharField(db_index=True, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='intakelog',
            name='time_window',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], max_length=16),
        ),
        migrations.AddField(
            model_name='intakelog',
            name='appliances',
            field=models.ManyToManyField(related_name='intake_logs', to='core.appliance'),
        ),
    ]
