# Generated by Django 5.1.4 on 2025-09-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appliance_remove_intakelog_appliance_intakelog_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakelog',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
