# Generated by Django 5.2.4 on 2026-05-02 23:56

from django.db import migrations, models
from django.db.models import Count


DEFAULT_SLOT_CAPACITY = 5


def backfill_appointment_slots(apps, schema_editor):
    AppointmentSlot = apps.get_model('core', 'AppointmentSlot')
    IntakeLog = apps.get_model('core', 'IntakeLog')

    slot_totals = (
        IntakeLog.objects.values('appointment_date', 'time_window')
        .annotate(total=Count('id'))
    )

    for slot_total in slot_totals:
        total = slot_total['total']
        AppointmentSlot.objects.update_or_create(
            appointment_date=slot_total['appointment_date'],
            time_window=slot_total['time_window'],
            defaults={
                'capacity': max(DEFAULT_SLOT_CAPACITY, total),
                'booked_count': total,
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_intakelog_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('time_window', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], max_length=16)),
                ('capacity', models.PositiveSmallIntegerField(default=5)),
                ('booked_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('appointment_date', 'time_window'), name='unique_appointment_slot')],
            },
        ),
        migrations.RunPython(backfill_appointment_slots, noop_reverse),
    ]
